---
title: "UM Applied Statistics Reading Group"
---

---

## Welcome!

We're a group of graduate students in the Department of Statistics at the University of Michigan interested in applications of statistics to problems of societal interest. Our reading group is meant to be a relaxed environment for discussion, clarification, and inquiry into the many challenges of deploying statistics in the real world.

___

## Fall 2021

Focus: Applications in medicine, public policy, and the health sciences.

Time: TBD, but will be bi-weekly

Date |Presenter | Paper                                   | Notes
-------|----------|-----------------------------------------|---------
Oct 8 | Nora Yujia | Evaluation of a Booster Dose (Third Dose), Vaccine and Related Biological Products Advisory Committee Briefing Document | https://www.fda.gov/media/152161/download


___

## Spring/Summer 2021

Focus: Applications in medicine, public policy, and the health sciences. Additionally, inspired by the  <a href="https://rlbarter.github.io/Practical-Statistics/about/">Practical Statistics</a> group at Berkeley, we will cover methods that are commonly used in statistical applications (especially in other disciplines) but not often taught in statistics courses.

Time: Every other Tuesday, 2-3pm EST

Date |Presenter | Paper                                   | Notes
-------|----------|-----------------------------------------|---------
May 17 | Nora Yujia | Mental Health Challenges of United States Healthcare Professionals During COVID-19 (Pearman et al. 2020) & A Primer on (M)AN(C)OVA |
June 1 | Laura | Multilevel Modeling: A Review of Methodological Issues and Applications (Dedrick et al. 2009) |
June 15 | Zoe | Multilevel and spatial analyses of childhood malnutrition in Uganda: examining individual and contextual factors (Amegbor et al. 2020) |
June 28 | Heather | A geographically weighted regression to estimate the comprehensive cost of traffic crashes at a zonal level (Hezaveh et al. 2019) |           
July 13 | Drew | "Missing Data in Longitudinal Studies - Part B: Analytic Issues" (Siddique et al. 2008) |
July 27 | Rob | "Greater Racial and Ethnic Disparities in COVID-19 Burden After Accounting for Missing Race and Ethnicity Data" (Labgold et al. 2021) |            
Aug 10 | Avery | "Estimating causal effects from observational data with a model for multiple bias" (Höfler et al. 2007) | 
Aug 23 | Rayleigh | "Dynamic Ideal Point Estimation via Markov Chain Monte Carlo for the U.S. Supreme Court, 1953–1999" (Martin and Quinn 2002) |  
___

## Winter 2021

Focus: Applications in medicine, public policy, and the health sciences

Time: Every other Tuesday, 3-4pm EST  ~~Every other Friday, 3-4pm EST~~

Date |Presenter | Paper                                   | Notes
-------|----------|-----------------------------------------|---------
Jan 29 | Nora Yujia               | Synthetic Control Methods for Comparative Case Studies: Estimating the Effect of California’s Tobacco Control Program” (Abadie, Diamond and Hainmueller, 2010)
Feb 12 | Rob                 | Estimating causal effects of air quality regulations using principal stratification for spatially correlated multivariate intermediate outcomes (Zigler, Dominici, and Wang, 2012) | 
Mar 3 | Drew | From hype to reality: data science enabling personalized medicine (Fröhlich et al. 2018) | 
Mar 16 | Zoe | The effect of differential victim crime reporting on predictive policing systems (Akpinar, De-Arteaga, and Chouldechova, 2021) | Time change: 3:30-4:30pm EST!
Mar 30 | Yujia               | Value-Added and Student Growth Percentile Models: What Drives Differences in Estimated Classroom Effects? (Kurtz 2018)
Apr 20 | Rob               | Bayesian Statistics for Beginners
